//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Employees')
export class EmployeesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  EmployeeID: string;

  @Column('text', { nullable: true })
  FirstName: string;

  @Column('text', { nullable: true })
  LastName: string;

  @Column('text', { nullable: true })
  MiddleName: string;

  @Column('date', { nullable: true })
  DateOfBirth: Date;

  @Column('text', { nullable: true })
  Gender: string;

  @Column('text', { nullable: true })
  Nationality: string;

  @Column('text', { nullable: true })
  MaritalStatus: string;

  @Column('text', { nullable: true })
  ContactInformation: string;

  @Column('text', { nullable: true })
  Address: string;

  @Column('text', { nullable: true })
  Department: string;

  @Column('text', { nullable: true })
  Position: string;

  @Column('text', { nullable: true })
  Manager: string;

  @Column('text', { nullable: true })
  EmploymentType: string;

  @Column('date', { nullable: true })
  StartDate: Date;

  @Column('date', { nullable: true })
  EndDate: Date;

  @Column('text', { nullable: true })
  SalaryInformation: string;

  @Column('text', { nullable: true })
  ProfilePicture: string;
}
