//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Evaluations')
export class EvaluationsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  ReviewID: number;

  @Column('integer', { nullable: true })
  EmployeeID: number;

  @Column('date', { nullable: true })
  PeriodStart: Date;

  @Column('date', { nullable: true })
  PeriodEnd: Date;

  @Column('text', { nullable: true })
  GoalsObjectives: string;

  @Column('text', { nullable: true })
  Achievements: string;

  @Column('text', { nullable: true })
  ImprovementAreas: string;

  @Column('text', { nullable: true })
  FeedbackfromSupervisor: string;

  @Column('text', { nullable: true })
  OverallRating: string;

  @Column('text', { nullable: true })
  Recommendations: string;
}
