//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Leaverequests')
export class LeaverequestsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  RequestID: number;

  @Column('integer', { nullable: true })
  EmployeeID: number;

  @Column('text', { nullable: true })
  TypeofLeave: string;

  @Column('date', { nullable: true })
  StartDate: Date;

  @Column('date', { nullable: true })
  EndDate: Date;

  @Column('text', { nullable: true })
  Reason: string;

  @Column('text', { nullable: true })
  ApprovalStatus: string;

  @Column('integer', { nullable: true })
  ApproverUserid: number;
}
