//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Payroll')
export class PayrollEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  PayrollID: number;

  @Column('integer', { nullable: true })
  EmployeeID: number;

  @Column('date', { nullable: true })
  PeriodStartDate: Date;

  @Column('date', { nullable: true })
  PeriodEndDate: Date;

  @Column('real', { nullable: true })
  GrossSalary: number;

  @Column('real', { nullable: true })
  Deductions: number;

  @Column('real', { nullable: true })
  NetSalary: number;

  @Column('date', { nullable: true })
  PayDate: Date;

  @Column('real', { nullable: true })
  OvertimeHours: number;

  @Column('real', { nullable: true })
  OvertimePay: number;
}
