//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const EmployeesTitle = () => {
  const record = useRecordContext();
  return <span>Employees {record ? `"${record.MiddleName}"` : ''}</span>;
};

export const EmployeesList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="EmployeeID" />
      <TextField source="FirstName" />
      <TextField source="LastName" />
      <TextField source="MiddleName" />
      <DateField source="DateOfBirth" />
      <TextField source="Gender" />
      <TextField source="Nationality" />
      <TextField source="MaritalStatus" />
      <TextField source="ContactInformation" />
      <TextField source="Address" />
      <TextField source="Department" />
      <TextField source="Position" />
      <TextField source="Manager" />
      <TextField source="EmploymentType" />
      <DateField source="StartDate" />
      <DateField source="EndDate" />
      <TextField source="SalaryInformation" />
      <ImageField source="ProfilePicture" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const EmployeesEdit = () => (
  <Edit title={<EmployeesTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="EmployeeID" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FirstName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="LastName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="MiddleName" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="DateOfBirth" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Gender" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Nationality" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="MaritalStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ContactInformation" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Address" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Department" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Position" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Manager" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="EmploymentType" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="StartDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="EndDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="SalaryInformation" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="ProfilePicture" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const EmployeesCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="EmployeeID" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FirstName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="LastName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="MiddleName" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="DateOfBirth" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Gender" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Nationality" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="MaritalStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ContactInformation" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Address" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Department" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Position" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Manager" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="EmploymentType" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="StartDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="EndDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="SalaryInformation" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="ProfilePicture" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
