//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const LeaverequestsTitle = () => {
  const record = useRecordContext();
  return (
    <span>Leaverequests {record ? `"${record.ApproverUserid}"` : ''}</span>
  );
};

export const LeaverequestsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="RequestID" />
      <ReferenceField source="EmployeeID" reference="Employees" />
      <TextField source="TypeofLeave" />
      <DateField source="StartDate" />
      <DateField source="EndDate" />
      <TextField source="Reason" />
      <TextField source="ApprovalStatus" />
      <ReferenceField source="ApproverUserid" reference="Users" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const LeaverequestsEdit = () => (
  <Edit title={<LeaverequestsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="RequestID" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="EmployeeID" reference="Employees" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="TypeofLeave" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="StartDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="EndDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Reason" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ApprovalStatus" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ApproverUserid" reference="Users" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const LeaverequestsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="RequestID" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="EmployeeID" reference="Employees" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="TypeofLeave" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="StartDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="EndDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Reason" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ApprovalStatus" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ApproverUserid" reference="Users" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="EmployeeID"
    label="EmployeeID"
    reference="Employees"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="ApproverUserid"
    label="ApproverUserid"
    reference="Users"
    alwaysOn
  />,
];
