//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const PayrollTitle = () => {
  const record = useRecordContext();
  return <span>Payroll {record ? `"${record.id}"` : ''}</span>;
};

export const PayrollList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="PayrollID" />
      <ReferenceField source="EmployeeID" reference="Employees" />
      <DateField source="PeriodStartDate" />
      <DateField source="PeriodEndDate" />
      <NumberField source="GrossSalary" />
      <NumberField source="Deductions" />
      <NumberField source="NetSalary" />
      <DateField source="PayDate" />
      <NumberField source="OvertimeHours" />
      <NumberField source="OvertimePay" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const PayrollEdit = () => (
  <Edit title={<PayrollTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="PayrollID" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="EmployeeID" reference="Employees" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="PeriodStartDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="PeriodEndDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="GrossSalary" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="Deductions" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="NetSalary" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="PayDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="OvertimeHours" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="OvertimePay" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const PayrollCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="PayrollID" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="EmployeeID" reference="Employees" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="PeriodStartDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="PeriodEndDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="GrossSalary" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="Deductions" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="NetSalary" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="PayDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="OvertimeHours" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="OvertimePay" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="EmployeeID"
    label="EmployeeID"
    reference="Employees"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
